### ISSUE TITLE
launch error on win8.1

### ISSUE THREAD

**Issue by emacs-newer** [glzr-io/glazewm#275]
i use this to start on my computer

https://github.com/lars-berger/GlazeWM/releases/download/v1.11.1/GlazeWM_x86_1.11.1.exe

which get error as bellow:

```
2023/2/27 15:08:37
System.EntryPointNotFoundException: Entry point was not found.
   at GlazeWM.Infrastructure.WindowsApi.WindowsApiService.SetProcessDpiAwarenessContext(DpiAwarenessContext value)
   at GlazeWM.Bootstrapper.Startup.Run() in C:\Users\larsb\repos\GlazeWM\GlazeWM.Bootstrapper\Startup.cs:line 47
Command history: HandleFatalExceptionCommand 
State dump: {"X":0,"Y":0,"Width":0,"Height":0,"__type":"RootContainer","FocusIndex":0,"Children":[]}
```

**Comment by lars-berger** [comment]
There's bound to issues with Windows 8 since I don't have a machine to test with. [`SetProcessDpiAwarenessContext`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext) is used to set the default DPI awareness and requires Windows 10. We could replace the call with [`SetProcessDpiAwareness`](https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-setprocessdpiawareness) instead for users on Windows 8.

Only Windows 10/11 are officially supported. If it all it takes to support Windows 8 is to replace that API call, then it'd be worth making the addition.  If you want to attempt the fix, feel free.
