### ISSUE TITLE
Avoid trying to manage windows running with elevated privileges

### ISSUE THREAD

**Issue by lars-berger** [glzr-io/glazewm#32]
Windows launched with administrator mode cannot be moved/resized when the WM is run in non-administrator mode.

These windows should be ignored when the WM is launched in non-administrator mode. If the WM is launched in administrator mode, then these windows should be managed.

**Comment by roblarky** [comment]
There are a set of conditions which allow managing elevated windows from a non-elevated app.

uiAccess true in manifest
Signed executable
Installed within Program Files folder

These will also allow the app to start with Windows with these elevated privileges.

I can give more information if you want to pursue this avenue, as this is what I do for StrokesPlus.net

**Comment by lars-berger** [comment]
Wow, that actually sounds very interesting. I'd assume this would also get rid of the annoying security warning when launching the unsigned `.exe`.

Changing the `uiAccess` in the manifest should be easy enough, but completely unfamiliar with creating MSI installers and signing executables. What tools did you end up using?

**Comment by roblarky** [comment]
In the original version of StrokesPlus, I just made my own certificate (Google around, pretty easy to do), and the installer would add the cert as trusted on the user's system. I use Inno Setup for my installers, just because it's really simple and lets you do whatever you want without a lot of fuss.

So the installer itself would give a smart scan warning and require elevation to run, but after that, it would start with Windows (no prompts) and be able to interact with elevated windows. Note that it needs to be installed under Program Files as I mentioned above.

The Smart Scan / security warning is a bit trickier. First, you have to purchase an actual code signing certificate, and in general will take time for Smart Scan to see the app being installed by various users without incident and eventually you'll pass the check. This is about the most affordable option, but you will have to gather documentation and have a notary verify you are who you are and your address. [https://www.ksoftware.net/code-signing-certificates/](https://www.ksoftware.net/code-signing-certificates/) 

So my post build event signs the EXE:
`"C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe" sign /a /v /n "{CERT_NAME}" /t http://timestamp.sectigo.com "StrokesPlus.net.exe"`

Then runs Inno Setup to create the installer (which is also configured to run the signtool on the setup exe when complete):
`"C:\Program Files (x86)\Inno Setup 6\Compil32.exe" /cc ..\..\InnoSetup\StrokesPlus.net_Setup.iss`

Now that StrokesPlus.net has been around a while, I don't think the Smart Scan warning appears anymore - but I suppose I'd need to do it on a fresh system to confirm, lol.

**Comment by lars-berger** [comment]
The application is now signed and `uiAccess` is enabled 🎉 Admin windows can finally be managed without running the WM as admin
