### ISSUE TITLE
window unmaximized when workspace is refocused

### ISSUE THREAD

**Issue by crhf** [glzr-io/glazewm#326]
A previously maximized window is unmaximized when its workspace is focused with Alt+<num>.

More details: I have two monitors, one has workspace 1, the other has workspace 2. After opening two windows in workspace 2 and  maximizing one of the windows, do Alt+1 then Alt+2. The previously maximized window is unmaximized, but I would expect it to stay exactly as it was (maximized).

Any way around this? Is this a feature or a bug?

**Comment by activaigor** [comment]
it is also being reset while switching with a recent workspace command. are there any workarounds?

**Comment by wis** [comment]
As a former i3 user, I got used to and do prefer the behavior of keeping the window maximized on the previous workspace when you change a workspace, so that when you go back to the previous workspace the window is still maximized and not unmaximized.
is there a config option to change/toggle off this behavior?

**Comment by Video-Nomad** [comment]
I believe this was fixed in the (#421) but it is not reflected in the provided binary. Just compile the latest develop version and you should be set.

**Comment by wis** [comment]
Thanks George @Video-Nomad, you're right, it is fixed by the latest commits. the window stays maximized when you go back to the workspace it is in. but there are some bugs that need reporting, like if window is maximized you `focus left` or right, the maximized window goes behind the focused window and you can't focus it it again without using the mouse.

**Comment by lars-berger** [comment]
Fixed in v3 👍 [Latest release](https://github.com/glzr-io/glazewm/releases)
