### ISSUE TITLE
Focus Border Width

### ISSUE THREAD

**Issue by alamb3142** [glzr-io/glazewm#507]
Is there any way to set the width in the `focus_borders` section? I can't see anything about it in the docs & I'd like to up it by a pixel or two.

**Comment by alamb3142** [comment]
On a similar note is there a setting to control the general border radius? There seems to be one on the status bar but not for windows in general

**Comment by FrancisTheCat** [comment]
I think because that functionality is actually provided by windows, you cant customize window borders. It works for the bar because thats drawn an other way. However I think you can change the border radius to be slightly smaller:
https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners
Beyond that I doubt its possible to do much.
Btw, ive got a tool on my github to remove window title bars wich could be modified really easily to set the window corner radius to the alternative smaller value

**Comment by alamb3142** [comment]
Going to close this as it appears to be a limitation of Windows APIs

**Comment by BobTB** [comment]
How does Komorebi do this? It has a configurable thickness focus border.

**Comment by FrancisTheCat** [comment]
> How does Komorebi do this? It has a configurable thickness focus border.

It seems to me like they create a separate window:
https://github.com/LGUG2Z/komorebi/blob/master/komorebi/src/border.rs

**Comment by aaronedev** [comment]
damn fkn windows api i wish i could border_width="2px"

**Comment by aaronedev** [comment]
> damn fkn windows api i wish i could border_width="2px"

or even god damn 3 god fucking pixels! imagin having a 3px border dawg - no mexicans would even be able to cross that thick wall
