### ISSUE TITLE
picture in picture on top

### ISSUE THREAD

**Issue by AmineDjeghri** [glzr-io/glazewm#537]
By default, picture in picture mode should keep the video on top of all windows. However, when using glazewm, once you click on another window, the pip window will go to the back .
Any fix / trick to this ?

**Comment by HemendraSinghShekhawat** [comment]
You can use Microsoft Powertoys for that,
So install Microsoft Powertoys from https://github.com/microsoft/PowerToys/releases/tag/v0.79.0 or from Windows Store
Open Powertoys and make sure "Always on Top" toggle is turned on
`Win + Ctrl + T` will activate the always on top

I know OP knows about below refernece, but for someone else
refer to : https://github.com/glzr-io/glazewm/issues/479 to ignore Picture in Picture for Glaze WM.

**Comment by AmineDjeghri** [comment]
Yes. The thing is that it works only for the current workspace and not across workspaces.  I think it would be great to have it work between workspaces.

**Comment by HemendraSinghShekhawat** [comment]
Reference => https://github.com/glzr-io/glazewm/issues/479#issuecomment-1860146569

This code if added to config should work for most **chromium based browsers** and is from the above comment
I don't know about **Chrome** though, because I don't use it.
If it is not working can you try using some different browser, and tell here about it.

`# Do not manage Picture-in-picture windows
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"`

I suppose this helps, If not please let me know.

**Comment by AmineDjeghri** [comment]
i just updated windows, and it works now.
