### ISSUE TITLE
[Feature Request] Add dwindle layout

### ISSUE THREAD

**Issue by CilekciGs** [glzr-io/glazewm#586]
Could we have dwindle layout like bspwm? [More info](https://dwm.suckless.org/patches/fibonacci/)

**Comment by Dreded** [comment]
I would also really really like this as well as a master style layout. having the windows constantly narrow everything makes little sense to me

I would think a master layout would be easy to achieve... more than two widows auto switch to open new ones vertically, less than 2 switch back to horizontal

**Comment by ParasiteDelta** [comment]
Well, there's two main challenges with this so far: implement a mode system, and implement the modes internally. I say internally because [Burgr033 already made a Dwindle layout using Python and the IPC](https://github.com/burgr033/GlazeWM-autotiling-python), which [I then shamelessly took and reimplemented in Rust.](https://github.com/ParasiteDelta/GlaAlt) There's also another thing to consider, however, and that is the current overhaul.

For V3, Lars is planning on rewriting the entirety of GWM in Rust. At the time of writing, he says that he's about halfway done, so even if someone were to create and implement this modal system, it would likely be a while before it was reviewed, merged, and released.

**Comment by lars-berger** [comment]
Closing in favor of #678

**Comment by HarshalGunjalOp** [comment]
> Could we have dwindle layout like bspwm? [More info](https://dwm.suckless.org/patches/fibonacci/)

I would also really like this feature to be implemented.

**Comment by Zackorus** [comment]
For all those who wanted the dwindle layout (automatic) it is here: https://github.com/Zackorus/glazewm

**Comment by rix7kz** [comment]
i want anyone to add bsp layout in glazewm that will be helpfull if anyone can do the please try to do

**Comment by Zackorus** [comment]
<img width="1914" height="1079" alt="Image" src="https://github.com/user-attachments/assets/46cc4d8a-d252-44e3-bd59-fab0d5b873f6" /> https://github.com/Zackorus/glazewm
