### ISSUE TITLE
On Crash or Close, Make Background Process into Apps again.

### ISSUE THREAD

**Issue by gvnmcg** [glzr-io/glazewm#607]
In the Task Manager: I see when programs are in the current workspace, they are Apps, and when they are not on the current workspace, they become Background Processes. 

After a crash or close, they are still background processes. 

I can end the tasks and Resume them, so this is of little importance.

**Comment by MoaidHathot** [comment]
@gvnmcg, I'm not sure this is a  little problem, I actually think this is a very important issue. I had around 7 different workspaces setup for work meetings and online sessions that I'm delivering. They contained open links, documents, terminal sessions, etc...
After GlazeWM crashed, I lost access to all of them. I can't even see what is the reason of the crash since I can't go back to the workspace containing the terminal. I had to restart my Machine 2 minutes before my sessions just because some apps and sessions can't be opened multiple times (in addition to memory/CPU constraints).

Maybe a solution could be to persist the workspaces? So that if GlazeWM is opened again after a crash it can recreate the last GlazeWM session?

**Comment by giulpig** [comment]
@MoaidHathot This issue affected me too, and honestly i find it to be a pain.
I found a workaround by using a software called GUIPropView as proposed in [this comment](https://github.com/glzr-io/glazewm/issues/448#issuecomment-1925864609)

**Comment by MoaidHathot** [comment]
Thanks @giulpig, I'll check it out

**Comment by lars-berger** [comment]
Restoring windows on exit has been overhauled in v3 - it should be a lot more stable now 👍
