### ISSUE TITLE
File Properties window not being handled

### ISSUE THREAD

**Issue by Doomwhite** [glzr-io/glazewm#643]
It seems like the properties windows are not being handled, I tried opening the properties of the glaze watcher itself, and it kept hiding from the screen.

https://github.com/user-attachments/assets/7117a7d0-5983-4ce1-8fdf-45092d050875

**Comment by lars-berger** [comment]
@Doomwhite Is this with `general.focus_follows_cursor` enabled?

**Comment by Doomwhite** [comment]
> @Doomwhite Is this with `general.focus_follows_cursor` enabled?

Yes

**Comment by Doomwhite** [comment]
Tested turning it off, the property window then floats normally.

**Comment by lars-berger** [comment]
It's because `general.focus_follows_cursor` focuses whichever window is currently under the cursor. Since the cursor goes over the console window in the gif, that then gets focus. You can enable `state_defaults.floating.shown_on_top` when using `general.focus_follows_cursor` so that floating windows don't cause issues
