### ISSUE TITLE
Suggestion: Don't override alt+left/right arrows by default

### ISSUE THREAD

**Issue by ThePython10110** [glzr-io/glazewm#664]
Alt+left and alt+right are normally used for back and forward in Windows. I use these keyboard shortcuts all the time. GlazeWM overrides these to move focus left and right. Of course, you can always change that in the config file, but I feel like the default behavior shouldn't override things like this.

Of course, this might annoy all the non-Vim-users out there, but still.

**Comment by lars-berger** [comment]
Since the vim users are probably a bit more technically adept on average (and will have an easier time tweaking the config), I reckon it's best we leave these as is to make it more accessible for non-power users

And also the true vim users would be using something like vimium for browser navigation instead of alt+left/right 😉
