### ISSUE TITLE
Installing without admin privileges

### ISSUE THREAD

**Issue by franroa** [glzr-io/glazewm#669]
Hi, I am wondering if there is a possiblity of offering a exe file which can be executed without admin privileges. I have been using glazewm so far without needing it, but now zebar and glazewm offer the installation executable which force the admin permissions to be assigned

**Comment by ParasiteDelta** [comment]
It is unknown whether or not you joined their Discord server, so I'll recap and summarize.

Basically, they went the route of requiring Admin for install because GlazeWM as of V3 is now a Microsoft-signed application. This was driven mainly because of the <rather ridiculous> requirement that applications be signed and installed into Program Files to manage admin-based windows, as well as a number of "iS iT vIrUs?!?" complaints. 

At the moment, there is no portable or unsigned variant of the application available, and I'm not even sure that it's on the table. However, rather ironically, people have been questioning and complaining about this since V3's release, so Lars might be inevitably forced to push something out at a later date. 

If it's really a deal-breaker, then your only options are to either compile and run it yourself (which may or may not work, I have no idea what pipeline he has for the signing), or to stick with V2 for now. The V2 was *supposed* to be pushed to a kind of "legacy" or "V2" branch, but I didn't see anything like that the last time I looked, so support for V2 may just be axed altogether for the moment.

**Comment by franroa** [comment]
ok, thanks for the explanation. Then I will stick to the v2 for now

**Comment by star-in-the-jar** [comment]
It’s possible to run GlazeWM without admin rights using the MSI (administrative extract).

1. Download:
https://github.com/glzr-io/glazewm/releases/tag/v3.10.0
→ standalone x64 (MSI)

2. Extract without installing:
`msiexec /a standalone-glazewm-v3.10.0-x64.msi /qb TARGETDIR=C:\Users\<your-username>\Apps\GlazeWM`

3. Run:
`C:\Users\<your-username>\Apps\GlazeWM\PFiles64\glzr.io\GlazeWM\cli\glazewm.exe`

It starts within a few seconds and correctly picks up the config from:
`C:\Users\<your-username>\.glzr\glazewm\config.yml`

No admin rights are required at any step.
Zebar is optional and not required.

Note:
- The `PFiles64\...` path comes from the MSI layout and may change in future versions.
- This is not an official portable build, but a workaround using MSI extraction.
