### ISSUE TITLE
[Bug] STILL NO ACCURATE VERSIONING!

### ISSUE THREAD

**Issue by ParasiteDelta** [glzr-io/glazewm#722]
### Describe the bug

I've been testing out the latest rolling release, after the integration of the `set-tiling-direction` feature, and I found out that there is _still_ no proper versioning on the `wm` or `watcher` packages! This is very, VERY bad practice, as not only does it disrupt any kind of formal checking and management when using the packages through the Rust ecosystem, but it makes it extremely convoluted to check the packages at all; rather than using the runtime version to reliably check the potential functionality, for example, I now have to just try and parse the command list itself.

Please, for the love of god, update the versions in the respective `Cargo.toml` files. Hell, I think you can even assign that as a job within CI, where it can assign versions using the current commit hash, e.g. "3.1.1-ee86fbf", for the internal versioning and release versions when tagged as a release, e.g. "3.1.2".

### Reproduction

Download the rolling release directly from the repo and compile.
Attempt to use or do anything that relies upon the version data.
Realize that it's still set to 0.0.0 even after admitting that it was a problem.
Drink coffee and question your choices.

### Version number

0.0.0-ee86fbf/3.1.1-ee86fbf

**Comment by lars-berger** [comment]
Yo calm down a lil please. We do already set the version number for the installer executable, for the main WM binary and for the watcher. Ref:

![image](https://github.com/user-attachments/assets/fe64ecc7-5f33-459b-ac4b-d87aa875733e)
![image](https://github.com/user-attachments/assets/f2b296ce-70dd-4eab-a735-c2dd96bfd72c)

For local builds, the version number is set via the `VERSION_NUMBER` env variable, otherwise it defaults to `0.0.0` (e.g. `VERSION_NUMBER="3.1.1-ee86fbf" cargo run`). This is a convention yoinked from [mullvad](https://github.com/rust-lang/cargo/issues/6583#issuecomment-1702417194). Feel free to propose a different approach though, otherwise closing this for now.
