### ISSUE TITLE
Restore window/workspace state on next startup after a forceful exit

### ISSUE THREAD

**Issue by tgharib** [glzr-io/glazewm#79]
GlazeWM just froze on my PC, which is fine. I don't mind occassionaly restarting GlazeWM. Unfortunately, after having needed to kill it in Task Manager, all my windows except one window are hidden. I suppose this is because before the crash, I was on a workspace with only one window. After starting GlazeWM again, all the hidden windows remain hidden and I essentially lost all my unsaved progress.

There should be a more graceful way of handling crashes. Maybe unhide all windows on GlazeWM start? [nog](https://github.com/TimUntersberger/nog) actually saves all windows in a text file so on restart, not only does it unhide hidden windows but it also puts them in the right workspaces.

**Comment by tgharib** [comment]
If you find yourself in the same situation as I was where unsaved progress was hidden, then [WinLister by NirSoft](https://www.nirsoft.net/utils/winlister.html) has the ability to unhide hidden windows.

**Comment by lars-berger** [comment]
I agree forceful exits should be handled better - there shouldn't be a need to use a 3rd party tool to handle these shortcomings.

Killing the WM via Task Manager unfortunately prevents it from performing any cleanup. I've had the same happen before when a managed window goes fully unresponsive, since the Windows API methods for moving/resizing windows are synchronous and will wait until completion. Is there an error log in `C:\Users\<YOUR_USER>\.glaze-wm\errors.log`?

Many background processes actually make use of hidden windows (it's common for 100+ hidden windows to be running at once), so unhiding all windows will likely cause these to freak out. The idea of saving window/workspace state to a text file sounds pretty solid though. I think it would mean updating the text file after every state-altering command, and there's also the edge case where the user config is changed before the next startup. A cool side benefit of implementing something like this is that it would make it easy to implement a user config reload feature further down the line.

**Comment by tgharib** [comment]
> Is there an error log in `C:\Users\<YOUR_USER>\.glaze-wm\errors.log`?

Unfortunately, losing unsaved progress after a crash is a deal-breaker for me. I use this for work and I can already imagine being in a meeting, doing a screen-sharing presentation and one crash later, all my windows are hidden and I have to fiddle around in WinLister like an idiot. So after I uninstalled, I reflexively removed `~/.glaze-wm`. Opps.

I should add that [komorebi](https://github.com/LGUG2Z/komorebi) tackles this issue by simply minimizing windows rather than hiding them. I'm not implying this method is superior but I figured listing more possible solutions is better.

**Comment by LGUG2Z** [comment]
This is still an issue in `komorebi` for users who want to hide instead of minimize windows. The way I went about it is a little clunky, but hey, it works. 🤷

Every time an event occurs, [komorebi updates a local JSON file with the list of all known HWNDs across all workspaces](https://github.com/LGUG2Z/komorebi/blob/master/komorebi/src/process_event.rs#L474=). Then, if there is a crash or the process must be killed forcefully, the user can run the `restore-windows` command [to restore whatever HWNDs were saved in that file before the crash/kill](https://github.com/LGUG2Z/komorebi/blob/master/komorebic/src/main.rs#L1074=).

For regular process terminations (ie. ctrl-c), `komorebi` uses a [ctrl-c signal handler to restore all known HWNDs](https://github.com/LGUG2Z/komorebi/blob/master/komorebi/src/main.rs#L442=) before finally processing the ctrl-c and exiting the process.

Hope this helps!

**Comment by M7mdisk** [comment]
Any updates on this? 
I really like this WM but this is honestly a dealbreaker. having to go through a big hassle to unhide the apps is too much.
I am willing to work on a fix, any leads on how to start or how you want the fix to be implemented?

**Comment by michaelowens** [comment]
+1

Me and my SO both have been running GlazeWM for the past 1-2 weeks without many issues, but funnily enough we both had this happen today.

**Comment by notblam** [comment]
@M7mdisk I agree with your point.  This is the most serious, dealbreaking bug that exists in GWM.  I had intentions to investigate and hopefully fix it one day down the road, but I have some other priorities that I'd like to work on fist.

If your willing to take the lead on this, that would be awesome.  If your looking for some guidance, feel free to join the community discord and shoot me a ping.

**Comment by arminveres** [comment]
Any progress on this? I am not even able to restore the windows as suggested by @tgharib, which makes it quite painful to work with a crash.

**Comment by notblam** [comment]
> 

No one has started work on this yet.  If anyone wants to take a stab at it, feel free to join the discord.  Otherwise, I will try and fix it soon.

**Comment by notblam** [comment]
> Any progress on this? I am not even able to restore the windows as suggested by @tgharib, which makes it quite painful to work with a crash.

No one has started work on this yet. If anyone wants to take a stab at it, feel free to join the discord. Otherwise, I will try and fix it soon.

**Comment by dipta10** [comment]
> Any progress on this? I am not even able to restore the windows as suggested by @tgharib, which makes it quite painful to work with a crash.

@tgharib I've just downloaded [GUIPropView](https://www.majorgeeks.com/files/details/guipropview.html) and it seems to work.
It's somewhat helpful if I really need to restore the window.
Make sure to check `Child > Display Hidden Windows` after running the application.
Then right-click the window you wish to restore and select `Show Selected Window` and then again select `Switch To`.
Hope you might find this helpful.

**Comment by olivier-norture** [comment]
Using GuiProdView I also had to enable `TopLevel > Display Hidden Windows` to see all hidden windows.

**Comment by HolbyFPV** [comment]
Hidden windows are restored on crash in the current build.

**Comment by yavko** [comment]
> Hidden windows are restored on crash in the current build.

Doesn't work for me, I lose windows even on a `close` command. And I'm on version 2.1.1, which afaik is the latest

**Comment by HolbyFPV** [comment]
> > Hidden windows are restored on crash in the current build.
> 
> Doesn't work for me, I lose windows even on a `close` command. And I'm on version 2.1.1, which afaik is the latest

Appreciate the feedback.  Re-opening this issue while we investigate a better solution.

**Comment by lars-berger** [comment]
> > Hidden windows are restored on crash in the current build.
> 
> Doesn't work for me, I lose windows even on a `close` command. And I'm on version 2.1.1, which afaik is the latest

`close` is for closing the window (i.e. just a wrapper around sending a kill message to the window)

Restoring windows on exit has been overhauled in v3 - it should be a lot more stable now 👍

**Comment by Kribbage** [comment]
this still happens to me pretty often in 3.8.1 - can't even get guipropview or winlister to reveal the windows either.
